### ISSUE TITLE
Regression tests won't run in Python 3

### ISSUE THREAD

**Issue by pllim** [spacetelescope/pyraf#36] opened 2017-07-21 01:05 UTC
For example, see https://ssb.stsci.edu/pandokia/pandokia.cgi?query=summary&qid=3443

~~It is known that PyRAF will not support Python 3.~~ So the question is:
* Do we keep the tests in a special Python 2 environment when everything else moves to Python 3? Or...
* Do we stop testing PyRAF altogether? Or...
* Do we have someone who can fix them?

**Comment by cdsontag** [comment] 2017-07-21 03:59
Pey-Lian, I don't know why you say this is known. PyRAF does indeed work on Python 3. I converted it myself a few years ago (was one of the first of the SSB packages) and it is listed in the FAQ.

PyRAF uses 2to3 during install. 

You are not the first to assume this, oddly. I'm very curious about where this misinformation is coming from.

**Comment by pllim** [comment] 2017-07-21 04:07
Ah, yes. I keep dumping PyRAF and IRAF together in my brain because people usually use them together. Sorry for the confusion.

So, do you think these failures are not related to PyRAF? Do you have any insight why they are failing?

**Comment by cdsontag** [comment] 2017-07-21 14:32
Yep.  Looks like the test code itself (not PyRAF, but tests for PyRAF) simply needs to be made compatible.  In the case of the the erring `pyraf/using_tasks` tests, that looks like a simple change of `print` to `print()`.  Do you want to do that @pllim or shall I (with a few days)?

I was not aware that we had finally hooked up the PyRAF tests to a Python 3 test context (thanks! to whoever got that working).

**Comment by pllim** [comment] 2017-07-21 14:56
It's Joe. :)  I won't be able to do this soon, so please fix it if you can. Thank you!

**Comment by pllim** [comment] 2017-07-28 01:24
Let's wait till tests pass before closing. Thanks! :)

**Comment by cdsontag** [comment] 2017-08-03 14:01
The tests on Python3 are good now and passing today.  Closing this.  But @pllim feel free to re-open if you have further concerns.

**Closed by cdsontag** 2017-08-03 14:01 UTC
Labels: question

**Comment by olebole** [comment] 2018-02-26 12:38
Where are those tests? I'd like to use them as CI (regression) tests on Debian as well.

**Comment by pllim** [comment] 2018-02-26 14:18
Unfortunately, they are nowhere publicly accessible right now. I'll open a new issue to port them to this repo.
